version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: docker/streamlit_app.Dockerfile
    image: "hdb_frontend:0.1.0"
    ports:
      - 8501:8501
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: docker/fast_api.Dockerfile
    image: "hdb_backend:0.1.0"
    ports:
      - 8500:8500
    environment:
      - MLFLOW_TRACKING_URI=http://host.docker.internal:5005
      - MODEL_URI=bd0fbc471f004d54b70a74a218476f11
      - RUN_ID=194177493496013876
