files:
  derived_features:
    read_from_source: postgres
    params:
      table_name: "hdb_training_features"
      columns:
        - month
        - year
        - flat_type
        - storey_range
        - floor_area_sqm
        - flat_model
        - lease_age
        - no_of_malls_within_2_km
        - distance_to_nearest_malls
        - no_of_schools_within_2_km
        - distance_to_nearest_schools
        - no_of_parks_within_2_km
        - distance_to_nearest_parks
        - no_of_MRT_stations_within_2_km
        - distance_to_nearest_MRT_stations
        - region
        - resale_price

label_column: resale_price

process_train_data:
  ordinal_encoding:
    - storey_range

  train_test_val_split:
    train_size: 0.7
    test_size: # Split between test and eval, leave blank to only have train, test
    random_state: 42

model_params:
  chosen_model: "ebm" # ridge, lasso, ebm, randforest, xgboost

  ridge:
    model_name: "ridge"
    one_hot_encode: True
    scale_data: True
    params:
      random_state: 42 #Default: 42
      solver: auto #Default: auto
      alpha: 1.0 #Default:1.0

  lasso:
    model_name: "lasso"
    one_hot_encode: True
    scale_data: True
    params:
      random_state: 42 #Default: 42
      alpha: 1.0 #Default:1.0

  randforest:
    model_name: "randforest"
    one_hot_encode: True
    scale_data: False
    params:
      random_state: 42
      n_estimators: 100 #Default: 100
      max_depth: 10
      min_samples_leaf: 1 #Default: 1
      min_samples_split: 2 #Default: 2

  ebm:
    model_name: "ebm"
    one_hot_encode: True
    scale_data: False
    params:
      random_state: 42 #Default: 42
      max_bins: 256 #Default: 256
      max_interaction_bins: 32 #Default: 32
      interactions: 10 #Default: 10
      learning_rate: 0.01 #Default: 0.01
      inner_bags: 0 #Default: 0
      outer_bags: 8 #Default: 8
      min_samples_leaf: 2 #Default: 2
      max_leaves: 3 #Default: 3

  xgboost:
    model_name: "xgboost"
    one_hot_encode: True
    scale_data: False
    params:

mlflow:
  artifact_name: 'testing'
  experiment_name: "testing"
  description: 'testing'
  model_name: testing.joblib
  tags:
    model-architecture: "testing"

evaluator:
  rounding_last_n: 5
  feature_importance_top_n: 5
  no_of_cv_folds: 5 # Leave blank to use train-test or train-val-test split

optimisation_metric: "test_mean_squared_error" # metric for optimisation